version: 2
updates:
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "/backend"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
