services:
  backend:
    image: filipton/fkmtime-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fkmtime-backend
    ports:
      - '5000:5000'
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://root:password@database:5432/fkm_time
      - SOCKET_PATH=/app/sock/socket.sock
    env_file:
      - .env
    volumes:
      - sock:/app/sock
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 20s
      retries: 50
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    container_name: fkmtime-database
    ports:
      - '5432:5432'
    restart: unless-stopped 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fkm_time
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 5s
      timeout: 20s
      retries: 50

  nginx:
    image: filipton/fkmtime-nginx:latest
    restart: unless-stopped
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    container_name: fkmtime-nginx
    ports:
      - '80:80'
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy
      dozzle:
        condition: service_healthy

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle:/data
    ports:
      - "8080:8080"
    environment:
      DOZZLE_BASE: /logs
      DOZZLE_AUTH_PROVIDER: simple
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 50

volumes:
  database:
  sock:
