services:
  database:
    image: postgres:16
    container_name: fkmtime-test-database
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fkm_time_test
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 5s
      timeout: 20s
      retries: 50
  
  dummy_wca:
    container_name: fkmtime-test-dummy-wca
    restart: unless-stopped
    image: maxidragon/dummy-wca:latest
    ports:
    - "3000:3000"

  dummy_wca_live:
    container_name: fkmtime-test-dummy-wca-live
    restart: unless-stopped
    image: maxidragon/dummy-wca-live:main
    ports:
      - "4000:4000"

volumes:
  database:

