version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fkmtime-backend
    ports:
      - '5000:5000'
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://root@database:3306/fkm_time
      - WCA_LIVE_API_ORIGIN=https://live.worldcubeassociation.org/api
      - WCA_ORIGIN=https://www.worldcubeassociation.org
      - WCA_LIVE_DEV_API_ORIGIN=http://0.0.0.0:4000/api
    depends_on:
      - database

  database:
    container_name: fkmtime-database
    ports:
      - '3306:3306'
    restart: unless-stopped 
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_DATABASE="fkm_time" 
    build:
      context: ./
      dockerfile: db/Dockerfile
    volumes:
      - database:/var/lib/mysql

  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    container_name: fkmtime-nginx
    environment:
      - BACKEND_ORIGIN=https://fkm.lan/api
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  database:
