version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fkmtime-backend
    ports:
      - '5000:5000'
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://root@database:3306/fkm_time
      - WCA_LIVE_API_ORIGIN=https://live.worldcubeassociation.org/api
      - WCA_ORIGIN=https://www.worldcubeassociation.org
      - WCA_LIVE_DEV_API_ORIGIN=http://0.0.0.0:4000/api
    depends_on:
      - database

  database:
    container_name: fkmtime-database
    ports:
      - '3306:3306'
    restart: unless-stopped 
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_DATABASE="fkm_time" 
    build:
      context: ./
      dockerfile: db/Dockerfile
    volumes:
      - database:/var/lib/mysql

  admin-site:
    build:
      context: ./admin-site
      dockerfile: Dockerfile
    container_name: fkmtime-frontend
    volumes:
      - frontend_dist:/app/dist
    depends_on:
      - backend

  delegate_app:
    build:
      context: ./delegate_app
      dockerfile: Dockerfile
    container_name: fkmtime-delegate-app
    restart: unless-stopped
    volumes:
      - delegate_app_build:/app/build/web

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: fkmtime-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/frontend
      - delegate_app_build:/delegate
    depends_on:
      - admin-site
      - delegate_app


volumes:
  database:
  frontend_dist:
  delegate_app_build:
