services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: fkmtime-dev-backend
    network_mode: host
    volumes:
      - ./backend/src:/app/src
      - /tmp/sock:/app/sock
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://root:password@127.0.0.1:5433/fkm_time
      - WCA_LIVE_API_ORIGIN=http://0.0.0.0:4000/api
      - WCA_ORIGIN=http://0.0.0.0:3000
      - WCA_CLIENT_ID=example-application-id
      - WCA_CLIENT_SECRET=example-secret
      - SOCKET_PATH=/app/sock/socket.sock
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 20s
      retries: 50

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: fkmtime-dev-frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:5173"
    restart: unless-stopped

  database:
    image: postgres:16
    container_name: fkmtime-dev-database
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fkm_time
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 5s
      timeout: 20s
      retries: 50

  go_backup:
    image: huacnlee/gobackup:latest
    ports:
      - "2703:2703"
    volumes:
      - ./gobackup.yml:/etc/gobackup/gobackup.yml
    attach: false

  api_tester:
    build:
      context: ./backend/api-tester
      dockerfile: Dockerfile.dev
    container_name: fkmtime-dev-api-tester
    ports:
      - "5001:5001"
    environment:
      - SOCKET_PATH=/app/sock/socket.sock
    volumes:
      - ./backend/api-tester/src:/app/src
      - /tmp/sock:/app/sock
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
  
  dummy_wca:
    container_name: fkmtime-dummy-wca
    restart: unless-stopped
    image: maxidragon/dummy-wca:latest
    ports:
    - "3000:3000"

volumes:
  database:
