FROM node:18

RUN npm install -g @nestjs/cli

WORKDIR /app
ENV NODE_ENV development

COPY package*.json ./
RUN npm install

RUN touch /app/socket.sock
RUN chown node:node /app/socket.sock
RUN chmod 777 /app/socket.sock

COPY . .
RUN npx prisma generate

EXPOSE 5000
CMD [ "/app/entrypoint-dev.sh" ]