version: '3'

services:
  backend:
    build: .
    command: pnpm prisma-seed
    ports:
      - '5000:5000'
    network_mode: host
    restart: on-failure
    depends_on:
      - database

  database:
    image: mariadb
    ports:
      - '3306:3306'
    network_mode: host
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_DATABASE="fkm_time"