name: Publish nginx docker image

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'nginx/**'
      - 'nginx.Dockerfile'
      - '.github/workflows/publish-nginx-image.yml'

      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fkmtime/fkmtime-nginx

jobs:
   push:
      name: Push to ghcr.io
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup Docker buildx
          uses: docker/setup-buildx-action@v3
        - name: Log into registry ${{ env.REGISTRY }}
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.TOKEN_GITHUB }}
        - name: Extract Docker metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        - name: Build and push Docker image
          id: build-and-push
          uses: docker/build-push-action@v6
          with:
            context: ./
            file: nginx.Dockerfile
            push: true
            platforms: linux/amd64, linux/arm64
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max            