name: Test

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'admin-site/**'
      - '.github/workflows/test-frontend.yml'

jobs:
  test_frontend:
    name: Admin site frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "admin-site"
      - name: Install dependencies
        working-directory: 'admin-site'
        run: npm ci
      - name: Run ESlint
        working-directory: 'admin-site'
        run: npm run lint
      - name: Check formatting
        working-directory: 'admin-site'
        run: npm run format:check
      - name: Build frontend
        working-directory: 'admin-site'
        run: npm run build
