name: Test

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'delegate_app/**'

jobs:
  test_mobile:
    name: Delegate app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Install dependencies
        run: flutter pub get
        working-directory: 'delegate_app' 
      - name: Build apk
        run: flutter build apk
        working-directory: 'delegate_app' 
