name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_frontend:
    name: Admin site frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "admin-site"
      - name: Install dependencies
        working-directory: 'admin-site' 
        run: npm ci
      - name: Run ESlint
        working-directory: 'admin-site'
        run: npm run lint
      - name: Build frontend
        working-directory: 'admin-site' 
        run: npm run build

  test_backend:
    name: Backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "backend"
      - name: Install dependencies
        working-directory: 'backend' 
        run: npm install
      - name: Run ESlint
        working-directory: 'backend'
        run: npm run lint
      - name: Check formatting
        working-directory: 'backend'
        run: npm run format:check
      - name: Build backend
        working-directory: 'backend' 
        run: npm run build

  test_mobile:
    name: Delegate app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Install dependencies
        run: flutter pub get
        working-directory: 'delegate_app' 
      - name: Build apk
        run: flutter build apk
        working-directory: 'delegate_app' 
